name: "Bug Report"
description: "Report a bug or unexpected behavior."
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out this form to report a bug.
  - type: input
    id: summary
    attributes:
      label: Bug Summary
      description: Briefly describe the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the bug.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior / Logs
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: Operating System and Version
    validations:
      required: true
  - type: input
    id: de
    attributes:
      label: Desktop Environment (GNOME, KDE, etc.)
    validations:
      required: true
  - type: input
    id: x11_wayland
    attributes:
      label: Display Server (X11/Wayland)
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Additional Context or Screenshots
    validations:
      required: false
