name: Arch Linux AUR Package Update

on:
  workflow_run:
    workflows: [cmake]
    branches: [main]
    types: [completed]
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'packaging/archlinux/**'
      - '.github/workflows/**'

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Publish linux-wallpaperengine-git to the AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.2
        with:
          pkgname: linux-wallpaperengine-git
          pkgbuild: ./packaging/archlinux/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          force_push: 'true'
          test: true
          test_flags: --clean --cleanbuild --nodeps --nobuild
